"""Initial schema: users, listings, photos, events.

Hand-written rather than autogenerated, because autogenerate needs a live
database and the spec supplies the exact DDL. Section 2 of the build spec is
the source of truth; this file should read as a transcription of it.

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

COLLEGE = ("cc", "seas", "gs", "cbs", "sipa", "tc", "law", "gsas",
           "journalism", "mailman", "sps", "gsapp", "other")
GRADE = ("freshman", "sophomore", "junior", "senior", "masters", "phd", "alumni")
LOCATION = ("morningside", "manhattanville", "uws", "ues", "harlem",
            "washington_heights", "downtown", "brooklyn", "queens", "other")
CATEGORY = ("furniture", "appliances", "electronics", "textbooks", "clothing",
            "kitchen", "decor", "sports", "tickets", "other")
ITEM_CONDITION = ("used", "unused")
LISTING_STATUS = ("active", "sold", "delisted")
EVENT_TYPE = ("session_start", "feed_view", "filter_toggle", "listing_view",
              "contact_click", "listing_posted", "listing_edited", "listing_sold")

_TYPES = [
    ("college", COLLEGE),
    ("grade", GRADE),
    ("location", LOCATION),
    ("category", CATEGORY),
    ("item_condition", ITEM_CONDITION),
    ("listing_status", LISTING_STATUS),
    ("event_type", EVENT_TYPE),
]


def upgrade() -> None:
    # gen_random_uuid() lives here on Postgres 13+.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    for name, values in _TYPES:
        vals = ", ".join(f"'{v}'" for v in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({vals})")

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False, unique=True),
        sa.Column("user_name", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.Text()),
        sa.Column("nationality", sa.CHAR(2), nullable=False),
        sa.Column("college", postgresql.ENUM(name="college", create_type=False), nullable=False),
        sa.Column("grade", postgresql.ENUM(name="grade", create_type=False), nullable=False),
        sa.Column("location", postgresql.ENUM(name="location", create_type=False), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.text("now()")),
    )
    # The identity itself is Supabase's; this table only carries the profile.
    op.execute(
        "ALTER TABLE users ADD CONSTRAINT users_id_fkey "
        "FOREIGN KEY (id) REFERENCES auth.users(id)"
    )

    op.create_table(
        "listings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("category", postgresql.ENUM(name="category", create_type=False), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("condition", postgresql.ENUM(name="item_condition", create_type=False), nullable=False),
        sa.Column("status", postgresql.ENUM(name="listing_status", create_type=False),
                  nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.text("now()")),
        sa.Column("sold_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint("price_cents >= 0", name="ck_listings_price_nonneg"),
    )
    # The feed is ORDER BY created_at DESC over active rows, every time.
    op.create_index("ix_listings_active_recent", "listings",
                    ["created_at"], postgresql_where=sa.text("status = 'active'"))
    op.create_index("ix_listings_seller", "listings", ["seller_id"])

    op.create_table(
        "photos",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("listing_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("listings.id", ondelete="CASCADE"), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False, server_default="0"),
    )
    op.create_index("ix_photos_listing", "photos", ["listing_id", "sort_order"])

    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), primary_key=True),
        sa.Column("event_type", postgresql.ENUM(name="event_type", create_type=False), nullable=False),
        sa.Column("actor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("listing_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("listings.id")),
        sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_events_type_created", "events", ["event_type", "created_at"])
    op.create_index("ix_events_session", "events", ["session_id"])


def downgrade() -> None:
    op.drop_table("events")
    op.drop_table("photos")
    op.drop_table("listings")
    op.drop_table("users")
    for name, _ in reversed(_TYPES):
        op.execute(f"DROP TYPE IF EXISTS {name}")
