"""Write the corpus to ``data/`` as CSV and as a loadable ``seed.sql``.

CSV is the interchange format because it loads into Postgres with ``\\copy``, into
pandas with one call, and into a spreadsheet when somebody wants to eyeball it.
``seed.sql`` exists so the backend can bring a database up without running Python.

Conventions, chosen once so the loader does not have to guess:

* timestamps are ISO-8601 with a ``+00:00`` offset (the columns are ``timestamptz``)
* booleans are ``true`` / ``false``
* NULL is the empty field, which is what ``\\copy ... WITH (FORMAT csv, NULL '')``
  expects
* the header row uses the exact column names from UX_SPEC §4
"""

from __future__ import annotations

import csv
import datetime as dt
import os

from . import vocabularies as V

USER_COLUMNS = (
    "id", "email", "username", "display_name", "phone", "phone_contact_enabled",
    "nationality", "school", "grade", "zip_code", "default_radius_mi",
    "default_filter_same_zip", "default_filter_same_nationality",
    "default_filter_same_school", "is_verified", "status",
    "created_at", "updated_at",
)

LISTING_COLUMNS = (
    "id", "seller_id", "source", "title", "description", "category", "subcategory",
    "condition", "price_cents", "is_free", "is_negotiable", "zip_code", "status",
    "view_count", "save_count", "enquiry_count", "external_url",
    "posted_at", "sold_at",
)

PHOTO_COLUMNS = ("id", "listing_id", "url", "position", "created_at")
VIEW_COLUMNS = ("id", "listing_id", "viewer_id", "viewed_at", "surface")
SAVE_COLUMNS = ("id", "listing_id", "user_id", "created_at")
ENQUIRY_COLUMNS = ("id", "listing_id", "buyer_id", "channel", "created_at")
FILTER_EVENT_COLUMNS = ("id", "user_id", "filter_key", "value", "result_count", "created_at")

ZIP_COLUMNS = ("zip_code", "neighbourhood", "borough", "lat", "lon", "miles_from_campus")


def _render(value):
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dt.datetime):
        return value.replace(microsecond=0).isoformat() + "+00:00"
    return value


def write_csv(path, columns, rows):
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(columns)
        for row in rows:
            writer.writerow([_render(row[c]) for c in columns])
    return len(rows)


def _sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dt.datetime):
        return "'%s+00'" % value.replace(microsecond=0).isoformat()
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _insert_block(table, columns, rows, batch=500):
    if not rows:
        return ""
    out = []
    for start in range(0, len(rows), batch):
        chunk = rows[start:start + batch]
        values = ",\n  ".join(
            "(" + ", ".join(_sql_literal(row[c]) for c in columns) + ")"
            for row in chunk
        )
        out.append("INSERT INTO %s (%s) VALUES\n  %s;\n"
                   % (table, ", ".join(columns), values))
    return "\n".join(out)


def write_sql(path, users, listings, photos, views, saves, enquiries,
              filter_events, zip_rows):
    """A single file that creates the enum types, the ZIP table, and every row.

    Table DDL is deliberately *not* here -- that belongs to whoever owns the
    schema and the migrations. This file assumes the tables exist and fills them,
    except for the enums and the ZIP reference table, which are generated data.
    """
    parts = [
        "-- Columbia Market seed data",
        "-- Generated by seed/generate.py. Do not edit by hand.",
        "-- Enum values are transcribed from docs/UX_SPEC.md §4.5.",
        "",
        "BEGIN;",
        "",
        "-- Enum types (§4.5). Safe to skip if migrations already created them.",
        V.postgres_enum_ddl(),
        "",
        "-- ZIP reference table (§4.6). Static, never geocoded at request time.",
        "CREATE TABLE IF NOT EXISTS zip_reference (",
        "  zip_code          char(5) PRIMARY KEY,",
        "  neighbourhood     text NOT NULL,",
        "  borough           text NOT NULL,",
        "  lat               double precision NOT NULL,",
        "  lon               double precision NOT NULL,",
        "  miles_from_campus numeric(4,1) NOT NULL",
        ");",
        "",
        _insert_block("zip_reference", ZIP_COLUMNS, zip_rows),
        _insert_block("users", USER_COLUMNS, users),
        _insert_block("listings", LISTING_COLUMNS, listings),
        _insert_block("listing_photos", PHOTO_COLUMNS, photos),
        _insert_block("listing_views", VIEW_COLUMNS, views),
        _insert_block("saves", SAVE_COLUMNS, saves),
        _insert_block("enquiries", ENQUIRY_COLUMNS, enquiries),
        _insert_block("filter_events", FILTER_EVENT_COLUMNS, filter_events),
        "COMMIT;",
        "",
    ]
    body = "\n".join(parts)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(body)
    return len(body)


def export_all(out_dir, users, listings, photos, views, saves, enquiries,
               filter_events, zip_rows):
    os.makedirs(out_dir, exist_ok=True)
    written = {}
    written["users.csv"] = write_csv(
        os.path.join(out_dir, "users.csv"), USER_COLUMNS, users)
    written["listings.csv"] = write_csv(
        os.path.join(out_dir, "listings.csv"), LISTING_COLUMNS, listings)
    written["listing_photos.csv"] = write_csv(
        os.path.join(out_dir, "listing_photos.csv"), PHOTO_COLUMNS, photos)
    written["listing_views.csv"] = write_csv(
        os.path.join(out_dir, "listing_views.csv"), VIEW_COLUMNS, views)
    written["saves.csv"] = write_csv(
        os.path.join(out_dir, "saves.csv"), SAVE_COLUMNS, saves)
    written["enquiries.csv"] = write_csv(
        os.path.join(out_dir, "enquiries.csv"), ENQUIRY_COLUMNS, enquiries)
    written["filter_events.csv"] = write_csv(
        os.path.join(out_dir, "filter_events.csv"), FILTER_EVENT_COLUMNS, filter_events)
    written["zip_reference.csv"] = write_csv(
        os.path.join(out_dir, "zip_reference.csv"), ZIP_COLUMNS, zip_rows)
    write_sql(os.path.join(out_dir, "seed.sql"), users, listings, photos,
              views, saves, enquiries, filter_events, zip_rows)
    written["seed.sql"] = sum(written.values())
    return written
